site_name: Chef Mate
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    scheme: default
    primary: custom
    accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Download: download.md
  - FAQ: faq.md
  - Privacy Policy: privacy-policy.md
  - Terms of Use: terms-of-use.md
  - About: about.md
